lista-de-tarefas-igao/Controllers/TarefasController.cs
using lista_de_tarefas_igao.Models;
using Microsoft.AspNetCore.Mvc;

namespace lista_de_tarefas_igao.Controllers
{
    public class TarefasController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
        public JsonResult Index_SelecionarFiltro(string filtroNome, bool filtroCompleta)
        {
            Tarefa tarefa = new Tarefa();
            List<Tarefa> tarefas = new List<Tarefa>();

            if (string.IsNullOrEmpty(filtroNome) && filtroCompleta == false)
            {
                tarefas = tarefa.SelectTarefas();
            }
            else if (string.IsNullOrEmpty(filtroNome) && filtroCompleta == true)
            {
                tarefas = tarefa.SelectTarefasCompletas(filtroCompleta);
            }
            else if (!string.IsNullOrEmpty(filtroNome) && filtroCompleta == false)
            {
                tarefas = tarefa.SelectTarefasFiltradas(filtroNome);
            }
            else if (!string.IsNullOrEmpty(filtroNome) && filtroCompleta == true)
            {
                tarefas = tarefa.SelectTarefasCompletasFiltradas(filtroCompleta, filtroNome);
            }

            return Json(new JsonResult(tarefas)); 
        }
        public ActionResult Delete([FromRoute]int id)
        {
            Tarefa tarefa = new Tarefa();
            tarefa.DeleteTarefaById(id);
            return RedirectToAction("Index");
        }
        public ActionResult Editar([FromRoute] int? id) 
        {
            Tarefa tarefa = new Tarefa();
            if (id.HasValue)
            {
                int idInt = id.GetValueOrDefault();
                tarefa = tarefa.SelectTarefaById(idInt);
            }            

            return View(tarefa);
        }
        [HttpPost]
        public JsonResult Editar(Tarefa tarefa)
        {
            if (tarefa.Id != 0)
            {
                tarefa = new Tarefa { Id = tarefa.Id, Nome = tarefa.Nome, Descricao = tarefa.Descricao, Completa = tarefa.Completa };
                tarefa.UpdateTarefaById(tarefa);
            }
            else
            {
                tarefa = new Tarefa { Nome = tarefa.Nome, Descricao = tarefa.Descricao, Completa = tarefa.Completa };
                tarefa.CreateTarefa(tarefa);
            }

            return Json(new JsonResult(tarefa));
        }

    }
}

lista-de-tarefas-igao/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lista de Tarefas</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/lista_de_tarefas_igao.styles.css" asp-append-version="true" />
    <link href="https://cdn.datatables.net/v/dt/jq-3.7.0/dt-1.13.6/datatables.min.css" rel="stylesheet">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Tarefas" asp-action="Index">Lista de Tarefas</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Index">Home</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Lista de tarefas - <a asp-area="" asp-controller="Tarefas" asp-action="Index">Home</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="https://code.jquery.com/jquery-3.7.1.min.js" integrity="sha256-/JqT3SQfawRcv/BIHPThkBvs0OEvtFFmqPF/lYI/Cxo=" crossorigin="anonymous"></script>
    <script src="https://cdn.datatables.net/v/dt/jq-3.7.0/dt-1.13.6/datatables.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>